# Generated by Django 2.2.7 on 2020-04-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('SINDH', 'Sindh'), ('PUNJAB', 'Punjab')], max_length=20)),
                ('date', models.DateField()),
                ('total_suspected', models.IntegerField(default=0)),
                ('total_tested', models.IntegerField(default=0)),
                ('total_tested_positive', models.IntegerField(default=0)),
                ('total_tested_negative', models.IntegerField(default=0)),
                ('total_admitted', models.IntegerField(default=0)),
                ('total_discharged', models.IntegerField(default=0)),
                ('total_died', models.IntegerField(default=0)),
            ],
        ),
    ]
