# Generated by Django 3.0.5 on 2020-05-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('feedback', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction_model',
            fields=[
                ('entry_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('Predictions', models.FloatField(default=None)),
                ('Upper_confidence_interval', models.FloatField(default=None)),
                ('Lower_confidence_interval', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Cases',
            fields=[
                ('entry_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('province', models.CharField(choices=[('Sindh', 'Sindh'), ('Punjab', 'Punjab'), ('KP', 'KP'), ('KPTD', 'KPTD'), ('GB', 'GB'), ('AJK', 'AJK'), ('ICT', 'ICT'), ('Taftan_mobile_lab', 'Taftan_mobile_lab'), ('Balochistan', 'Balochistan')], max_length=20)),
                ('most_infected_city', models.CharField(default=None, max_length=50)),
                ('total_suspected', models.IntegerField(default=0)),
                ('total_tested', models.IntegerField(default=0)),
                ('total_tested_positive', models.IntegerField(default=0)),
                ('total_admitted', models.IntegerField(default=0)),
                ('total_discharged', models.IntegerField(default=0)),
                ('total_died', models.IntegerField(default=0)),
                ('datetime_of_entry', models.DateTimeField(default=None)),
            ],
            options={
                'verbose_name': 'Daily Cases',
                'verbose_name_plural': 'Daily Cases',
                'unique_together': {('date', 'province')},
            },
        ),
    ]
