# Generated by Django 2.2.7 on 2020-06-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='city_Data',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('district', models.CharField(max_length=250)),
                ('total', models.IntegerField(default=None)),
                ('casePerMillionPopulation', models.FloatField(default=None)),
                ('Population', models.IntegerField(default=None)),
            ],
        ),
    ]
