# Generated by Django 2.2.7 on 2020-04-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200402_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_offset', models.DateField()),
                ('no_of_cases', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='daily_cases',
            name='total_died',
            field=models.FloatField(default=0),
        ),
    ]
