# Generated by Django 2.2.7 on 2020-04-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200412_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction_model',
            name='day_offset',
            field=models.DateField(),
        ),
    ]
