# Generated by Django 2.2.7 on 2020-04-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_cases',
            name='total_died',
            field=models.IntegerField(default=0),
        ),
    ]
