# Generated by Django 2.2.7 on 2020-04-15 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200415_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prediction_model',
            old_name='day_offset',
            new_name='date',
        ),
    ]
