# Generated by Django 2.2.7 on 2020-04-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20200415_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_cases',
            name='id',
        ),
        migrations.AddField(
            model_name='daily_cases',
            name='entry_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
