# Generated by Django 2.2.7 on 2020-04-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20200423_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediction_model',
            name='id',
        ),
        migrations.AddField(
            model_name='prediction_model',
            name='entry_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='daily_cases',
            name='province',
            field=models.CharField(choices=[('Sindh', 'Sindh'), ('Punjab', 'Punjab'), ('KPK', 'KPK'), ('KPTD', 'KPTD'), ('GB', 'GB'), ('AJK', 'AJK'), ('ICT', 'ICT'), ('Taftan_mobile_lab', 'Taftan_mobile_lab'), ('Balochistan', 'Balochistan')], max_length=20),
        ),
    ]
