# Generated by Django 2.2.7 on 2020-04-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20200424_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_cases',
            name='datetime_of_entry',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='daily_cases',
            name='province',
            field=models.CharField(choices=[('Sindh', 'Sindh'), ('Punjab', 'Punjab'), ('KP', 'KP'), ('KPTD', 'KPTD'), ('GB', 'GB'), ('AJK', 'AJK'), ('ICT', 'ICT'), ('Taftan_mobile_lab', 'Taftan_mobile_lab'), ('Balochistan', 'Balochistan')], max_length=20),
        ),
    ]
