# Generated by Django 2.2.7 on 2020-04-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_most_infected_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediction_model',
            name='no_of_cases',
        ),
        migrations.AddField(
            model_name='prediction_model',
            name='Lower_confidence_interval',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='prediction_model',
            name='Predictions',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='prediction_model',
            name='Upper_confidence_interval',
            field=models.FloatField(default=0.0),
        ),
    ]
