# Generated by Django 2.2.7 on 2020-04-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20200426_1319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='most_infected_city',
        ),
        migrations.AddField(
            model_name='daily_cases',
            name='most_infected_city',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
