# Generated by Django 2.2.7 on 2020-06-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_city_data_province'),
        ('mainapp', '0014_auto_20200426_1545'),
    ]

    operations = [
    ]
