# Generated by Django 2.2.7 on 2020-06-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_merge_20200619_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balochistan_Data',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('district', models.CharField(max_length=250)),
                ('total', models.IntegerField(default=None)),
                ('casePerMillionPopulation', models.FloatField(default=None)),
                ('Population', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='KPK_Data',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('district', models.CharField(max_length=250)),
                ('total', models.IntegerField(default=None)),
                ('casePerMillionPopulation', models.FloatField(default=None)),
                ('Population', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Punjab_Data',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('district', models.CharField(max_length=250)),
                ('total', models.IntegerField(default=None)),
                ('casePerMillionPopulation', models.FloatField(default=None)),
                ('Population', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Sindh_Data',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('district', models.CharField(max_length=250)),
                ('total', models.IntegerField(default=None)),
                ('casePerMillionPopulation', models.FloatField(default=None)),
                ('Population', models.IntegerField(default=None)),
            ],
        ),
        migrations.DeleteModel(
            name='city_Data',
        ),
    ]
